using Microsoft.AspNetCore.Mvc;
using EventBookingBackend.Models;
using EventBookingBackend.Services;
using EventBookingBackend.DTOs;

namespace EventBookingBackend.Controllers
{
    // Handles booking API requests and delegates business rules to the booking service
    [Route("api/booking")]
    [ApiController]
    public class BookingController : ControllerBase
    {
        private readonly IBookingService _bookingService;
        public BookingController(IBookingService bookingService)
        {
            _bookingService = bookingService;
        }

        [HttpGet]
        public async Task<IActionResult> GetAllBooking()
        {
            var booking = await _bookingService.GetAllBookingAsync();
            return Ok(new
            {
                message = "Booking retrieved successfully.",
                data = booking
            });
        }

        [HttpGet("{bookingId}")]
        public async Task<IActionResult> GetBookingById(int bookingId)
        {
            var booking = await _bookingService.GetBookingByIdAsync(bookingId);
            if (booking == null)
            {
                return NotFound(new
                {
                    message = "Booking ID not found."
                });
            }

            return Ok(new
            {
                message = "Booking retrieved successfully.",
                data = booking
            });
        }

        [HttpGet("user/{userId}")]
        public async Task<IActionResult> GetBookingByUserId(int userId)
        {
            var booking = await _bookingService.GetBookingByUserIdAsync(userId);
            if (booking == null)
            {
                return NotFound(new
                {
                    message = "User ID not found."
                });
            }

            return Ok(new
            {
                message = "Booking retrieved successfully.",
                data = booking
            });
        }

        [HttpGet("event/{eventId}")]
        public async Task<IActionResult> GetBookingByEventId(int eventId)
        {
            var booking = await _bookingService.GetBookingByEventIdAsync(eventId);
            if (booking == null)
            {
                return NotFound(new
                {
                    message = "Event ID not found."
                });
            }


            return Ok(new
            {
                message = "Booking retrieved successfully.",
                data = booking
            });
        }


        [HttpPost("create/{userId}")]
        public async Task<IActionResult> CreateNewBooking([FromBody] CreateBookingRequest request, int userId)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(new
                {
                    message = "Validation failed.",
                    errors = ModelState
                });
            }

            // Only required booking input is mapped here. Other values are generated by the service
            var newBooking = new Booking
            {
                EventId = request.EventId,
                Quantity = request.Quantity
            };

            var booking = await _bookingService.CreateNewBookingAsync(newBooking, userId);
            if (booking == null)
            {
                return BadRequest(new
                {
                    message = "Booking failed. Event/user may not exist, event is not open, or ticket is not enough."
                });
            }
            return CreatedAtAction(
                nameof(GetBookingById), //  data can be checked using the GetBookingById method in this file
                new { bookingId = booking.BookingId }, // for passing parameter that is needed by GetBookingById
                new // response for JSON
                {
                    message = "Booking created successfully.",
                    data = booking
                });
        }

        [HttpPut("update/{bookingId}")]
        public async Task<IActionResult> UpdateBooking(int bookingId)
        {
            // Bookings are not updated directly to protect ticket and payment consistency
            return BadRequest(new
            {
                message = "Booking cannot be updated directly. Use cancel endpoint instead."
            });
        }
        [HttpPut("cancel/{bookingId}")]
        public async Task<IActionResult> CancelBooking(int bookingId)
        {
            // Cancellation rules, ticket restoration, and payment updates are handled in the service
            var booking = await _bookingService.CancelBookingAsync(bookingId);
            if (booking == null)
            {
                return BadRequest(new
                {
                    message = "Cancel booking failed. Booking may not exist or cannot be cancelled."
                });
            }

            return Ok(new
            {
                message = "Booking cancelled successfully.",
                data = booking
            });
        }
        [HttpPut("activate/{bookingId}")]
        public async Task<IActionResult> ActivateBooking(int bookingId)
        {
            // A booking can only be activated after its payment is successfully paid
            var booking = await _bookingService.ActivateBookingAsync(bookingId);
            if (booking == null)
            {
                return BadRequest(new
                {
                    message = "Can not activate. Booking ID not found, payment failed, or other reasons"
                });
            }

            return Ok(new
            {
                message = "Booking activated successfully.",
                data = booking
            });
        }


        [HttpDelete("delete/{bookingId}")]
        public async Task<IActionResult> DeleteBooking(int bookingId)
        {
            // Bookings must be cancelled before they can be deleted
            var booking = await _bookingService.DeleteBookingAsync(bookingId);
            if (booking == false)
            {
                return BadRequest(new
                {
                    message = "Delete booking is failed. Booking not found or booking must be cancelled before delete."
                });
            }

            return NoContent();
        }



    }
}