using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EventBookingBackend.Models
{
    // Represents a user's ticket booking for an event
    public class Booking
    {
        [Key]
        [Column("booking_id")]
        public int BookingId { get; set; }

        [Required]
        [Column("booking_code")]
        public string BookingCode { get; set; } = null!; // Generated by the service
        

        [Range(1, int.MaxValue, ErrorMessage = "Event is required.")]  // give range starting from 1 so that its valid, if 0 means invalid
        [Column("bookingEvent_id")]
        public int EventId { get; set; }


        [Range(1, int.MaxValue, ErrorMessage = "User is required.")]
        [Column("bookingUser_id")]
        public int UserId { get; set; }


        [Range(1, int.MaxValue, ErrorMessage = "Quantity must be at least 1.")]
        [Column("quantity")]
        public int Quantity { get; set; }


        [Column("ticket_price")]
        public decimal TicketPrice { get; set; } = 0; // Captures the event ticket price at booking time


        [Column("status")]
        public string Status { get; set; } = "Pending"; // Status: Pending, Active, or Cancelled.


        [Column("created_at")]
        public DateTime CreatedAt { get; set; } = DateTime.Now;


        [Column("cancelled_at")]
        public DateTime? CancelledAt { get; set; }
    }
}